stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: caesarteam/caesar-web-client:${CICD_GIT_BRANCH}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
- name: webhook
  steps:
  - runScriptConfig:
      image: caesarteam/alpine-curl
      shellScript: 'curl -X POST -H "Content-Type: application/json" -d ''{"name":
        "$CICD_GIT_REPO_NAME","tag": "$CICD_GIT_TAG"}'' $WEBHOOK_URL'
    envFrom:
    - sourceName: build-webhook
      sourceKey: WEBHOOK_URL
      targetKey: WEBHOOK_URL
  when:
    event:
      include:
      - tag
branch:
  include:
  - develop
  - master
notification:
  recipients:
  - recipient: '#pipeline'
    notifier: c-qzkvv:n-qqrqq
  condition:
  - Success
  - Changed
  - Failed
