stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: caesarteam/caesar-web-client:${CICD_GIT_BRANCH}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
    env:
      CICD_NAMESPACE: dev-caesar-team  
branch:
  include: [ develop, master ]
notification:
  recipients:
  - recipient: "#caesarapp-notify"
    notifier: "slack"
  condition: [ Success, Changed, Failed ]
