stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: caesarteam/caesar-web-client:${CICD_GIT_BRANCH}
      pushRemote: true
      registry: index.docker.io
    when:
      branch:
        include:
        - develop
        - hotfix/*
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: caesarteam/caesar-web-client:${CICD_GIT_TAG}
      pushRemote: true
      registry: index.docker.io
    when:
      event:
        include:
        - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
    when:
      branch:
        include:
        - develop
        - hotfix/*
notification:
  recipients:
  - recipient: https://chat.caesar.software/hooks/ZpopzncGgv9sqNfiP/As383iWceBGa2PvjDb9oZLR2rFfySCPX6idGS978Q7o6dKpG
    notifier: c-qzkvv:n-2bf45
  condition:
  - Success
  - Changed
  - Failed
