stages:
  - name: Publish image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: caesarteam/caesar-web-client:${CICD_GIT_BRANCH}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deploy/deployment.yaml