stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: caesarteam/caesar-web-client:${CICD_GIT_BRANCH}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
branch:
  include:
  - develop
  - master
notification:
  recipients:
  - recipient: https://chat.caesar.software/hooks/ZpopzncGgv9sqNfiP/As383iWceBGa2PvjDb9oZLR2rFfySCPX6idGS978Q7o6dKpG
    notifier: c-qzkvv:n-2bf45
  condition:
  - Success
  - Changed
  - Failed
