stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: caesarteam/caesar-web-client:${CICD_GIT_BRANCH}
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
branch:
  include:
  - develop
  - master
notification:
  recipients:
  - recipient: '#caesarapp-notify'
    notifier: c-5lcml:n-fdnnp
  condition:
  - Success
  - Changed
  - Failed
