version: '3'

services:
  web:
    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        API_URI: ${API_URI}
        APP_URI: ${APP_URI}
    environment:
      - API_URI
      - APP_URI
    ports:
      - "${EXTERNAL_PORT}:3000"
