version: '3'

services:
  web:
    image: caesarteam/caesar-web-client:develop
    build:
      dockerfile: ./Dockerfile
      context: ./
    env_file: .env.development
    ports:
      - '${EXTERNAL_PORT}:3000'
