apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: caesarapp-web-app
  labels:
    app: caesarapp-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caesarapp-web-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: caesarapp-web-app
    spec:
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: Always
      containers:
        containers:
          - name: caesarapp-web-app
            image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}
            imagePullPolicy: Always